site_name: 'CompbioZurich'
site_description: 'Computational Biology & Bioinformatics in the Zürich Area'
site_author: Michael Baudis
copyright: '&copy; 2022 Michael Baudis'
repo_name: 'compbiozurich.github.io'

repo_url: https://github.com/compbiozurich/compbiozurich.github.io
edit_uri: edit/main/docs/

###############################################################################

nav:
  - 'CompbioZurich': index.md
  - News & Events: news
  - Bioinformatics Groups: people
  - Lectures, Courses & Graduate Programs: teaching
  - Tools & Resources: resources
  - Positions: positions

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - extras/.icons

###############################################################################

theme:
  name: material
  palette:
    primary: purple
    accent: indigo
  favicon: img/favicon.ico
  logo: img/site_logo.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - toc.integrate
  custom_dir: extras
      
plugins:
    - search
    # - macros
    # - mermaid2

extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/compbiozurich
    - icon: fontawesome/brands/github 
      link: https://github.com/compbiozurich
extra_css:
  - css/theme_overrides.css
extra_javascript:
  # - /js/jquery-min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    
